CREATE TABLE IF NOT EXISTS DEVICE (
  ID VARCHAR(36) NOT NULL,
  CREATED_DATE DATETIME(3),
  VERSION INT(11),
  CAM_ID VARCHAR(255),
  DESCRIPTION VARCHAR(255),
  IMEI VARCHAR(255) NOT NULL,
  NAME VARCHAR(255),
  SERIAL_VERSION VARCHAR(255),
  TELEPHONE VARCHAR(255),
  IS_HIDDEN NUMBER(1) DEFAULT 0 NOT NULL,
  PRIMARY KEY (ID)
);

